<?php // Automatically Generated by TestLink Installer
    
define('DB_TYPE', 'postgres');
define('DB_USER', 'testlinkuser');
define('DB_PASS', 'testLinkUser@makkajai123');
define('DB_HOST', 'monster-math-competition-db.c3exe9kzzi00.us-west-2.rds.amazonaws.com:5432');
define('DB_NAME', 'Testlink');
define('DB_TABLE_PREFIX', '');
    
?>
